language: cpp
sudo: required
compiler:
  - clang
  - gcc
os:
  - linux
  - osx
branches:
  only:
  - master
  - stage
before_install:
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get -qq update && sudo apt-get install -y libunittest++-dev; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install unittest-cpp; fi
  - if [ $TRAVIS_OS_NAME == linux ] && [ "$CXX" == "clang++" ]; then sudo apt-get install -y clang-3.6 && export CXX="clang++-3.6"; fi 
install: cmake CMakeLists.txt
script: make && build/unitTests
after_script: rm -f *.hpl *.log
